run:
  timeout: 2m
  tests: true

linters:
  enable:
    - govet          
    - errcheck        
    - staticcheck    
    - gosimple        
    - unused          
    - deadcode        
    - typecheck       
    - revive          

linters-settings:
  revive:
    ignore-generated-header: true
    severity: warning
    rules:
      - name: indent-error-flow
      - name: blank-imports
      - name: var-naming
      - name: if-return

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  format: colored-line
  sort-results: true
