version: '3.8'

services:
  go-helloworld:
    image: golang-helloworld-diplom:latest 
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-helloworld
    ports:
      - "8080:8080"
    # environment: []  # если есть переменные окружения

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - go-helloworld

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
