version: '3.8'

services:
  go-helloworld:
    image: golang-helloworld-diplom:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-helloworld
    ports:
      - "8080:8080"
    restart: unless-stopped 

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - go-helloworld
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD_CHANGE=false
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_PATHS_PROVISIONING=/app/provisioning
    volumes:
      - ./provisioning/datasources:/app/provisioning/datasources
      - ./provisioning/dashboards:/app/provisioning/dashboards
    restart: unless-stopped



