version: '3.8'

services:
  go-helloworld:
    image: golang-helloworld-diplom:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-helloworld
    ports:
      - "8080:8080"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - go-helloworld

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_PASSWORD_CHANGE=false
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    volumes:
      - ./datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ./dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./node-exporter.json:/etc/grafana/provisioning/dashboards/node-exporter.json
      - ./go-app.json:/etc/grafana/provisioning/dashboards/go-app.json
      - ./prometheus-stats.json:/etc/grafana/provisioning/dashboards/prometheus-stats.json


