name: CI/CD

on:
  push:
    branches: [ "*" ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Run Linter
        run: go fmt ./...

      - name: Run Tests
        run: go test -v ./...

      - name: Build Go binary
        run: go build -v -o main .

      - name: Build Docker image
        run: docker build -t golang-helloworld:${{ github.sha }} .

      - name: Save artifact
        uses: actions/upload-artifact@v4
        with:
          name: golang-helloworld
          path: main

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy step (example)
        run: echo "Deploy step - тут ваша команда развёртывания"

      - name: Telegram notify
        if: always()                 # << === БУДЕТ ОТПРАВЛЯТЬСЯ ВСЕГДА
        env:
          BOT_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          message="🏁 CI завершён для ${GITHUB_REPOSITORY}\n\
Статус deploy: ${{ job.status }}\n\
Ветка: ${GITHUB_REF}\n\
Commit: ${GITHUB_SHA}\n\
Время: $(date '+%Y-%m-%d %H:%M:%S')"
          curl -s -X POST "https://api.telegram.org/8109888607:AAHK7Pd-irbxl9sVvYeBXAWVu3lC_Ibxg-s/sendMessage" \
            -d chat_id="${CHAT_ID}" \
            -d text="$message"
